amq:
  clientSecret: "![YOUR_ENCRYPTED_AMQ_CLIENT_SECRET]"
smtp:
  password: "![YOUR_ENCRYPTED_SMTP_PASSWORD]"
  user: "![YOUR_ENCRYPTED_SMTP_USER]"
src:
  password: "![YOUR_ENCRYPTED_SRC_SFDC_PASSWORD]"
  securityToken: "![YOUR_ENCRYPTED_SRC_SFDC_SECURITY_TOKEN]"
  username: "![YOUR_ENCRYPTED_SRC_SFDC_USERNAME]"
tgt:
  password: "![YOUR_ENCRYPTED_TGT_SFDC_PASSWORD]"
  securityToken: "![YOUR_ENCRYPTED_TGT_SFDC_SECURITY_TOKEN]"
  username: "![YOUR_ENCRYPTED_TGT_SFDC_USERNAME]"