amq:
  clientId: "YOUR_AMQ_CLIENT_ID"
  errHsptlWriteFailureQueue: "YOUR_AMQ_QUEUE_NAME"
  url: "YOUR_AMQ_URL"
batch:
  aggregatorSize:
    errHsptl: "YOUR_AGGREGATOR_SIZE_FOR_ERR_HSPTL"
    opp: "YOUR_AGGREGATOR_SIZE_FOR_OPP"
    oli: "YOUR_AGGREGATOR_SIZE_FOR_OLI"
  blockSize: "YOUR_BLOCK_SIZE"
errHsptl:
  maxRetries: "YOUR_MAX_RETRIES"
  retrieveLimit: "YOUR_RETRIEVE_LIMIT"
error:
  defaultDescription: "YOUR_DEFAULT_DESCRIPTION"
  defaultMessage: "YOUR_DEFAULT_MESSAGE"
  defaultType: "YOUR_DEFAULT_TYPE"
httpListener:
  port: "YOUR_HTTP_LISTENER_PORT"
  readTimeout: "YOUR_HTTP_LISTENER_READ_TIMEOUT"
orgName: "YOUR_ORG_NAME"
pbe.map.json: >
  {
    "SRC_to_TGT": {
      "YOUR_SRC_ID_1":  "YOUR_TGT_ID_1",
      "YOUR_SRC_ID_2": "YOUR_TGT_ID_2",
      "YOUR_SRC_ID_3": "YOUR_TGT_ID_3",
      "YOUR_SRC_ID_N": "YOUR_TGT_ID_N"
    }
  }
projectName: "YOUR_PROJECT_NAME"
scheduler:
  main:
    cronExpression: "YOUR_MAIN_CRON_EXPRESSION"
    timezone: "UTC"
  retry:
    cronExpression: "YOUR_RETRY_CRON_EXPRESSION"
    timezone: "UTC"
smtp:
  enable: "TRUE_OR_FALSE"
  host: "YOUR_SMTP_HOST"
  port: "YOUR_SMTP_PORT"
  subject:
    errHsptlError: "[YOUR_PROJECT_NAME] Error Hospital Write Error"
    batchSummary: "[YOUR_PROJECT_NAME] Batch Completion Error Summary"
    batchPreprocessingError: "[YOUR_PROJECT_NAME] Batch Pre-processing Error"
    batchPostprocessingError: "[YOUR_PROJECT_NAME] Batch Post-processing Error"
    healthCheckError: "[YOUR_PROJECT_NAME] Health Check Error"
  toEmailAddresses: "YOUR_TO_EMAIL_ADDRESSES"
src:
  authUrl: "YOUR_SRC_SFDC_AUTH_URL"
tgt:
  authUrl: "YOUR_TGT_SFDC_AUTH_URL"
watermark:
  timezone: "UTC"