httpListener:
  port: "8083"
  readTimeout: "30000"
batch:
  aggregatorSize: "100"
errHsptl:
  maxRetries: "5"
  retrieveLimit: "100"
orgName: "MNA-Tech"
projectName: "mna-oppty-mirror-accel"
scheduler:
  main:
    cronExpression: "0 0 * * * ?"
    timezone: "GMT"
  retry:
    cronExpression: "0 0/10 * * * ?"
    timezone: "GMT"
smtp:
  toAddress: "error_notifications@test.com"
src:
  pbEntryId:
    C: "01uKa00000AeCAcIAN"
    OT: "01uKa00000AeCAeIAN"
    OG: "01uKa00000AeCAdIAN"
tgt:
  pbEntryId:
    C: "01ugL000002WgsbQAC"
    OT: "01ugL000002WgkXQAS"
    OG: "01ugL000002WgkYQAS"
vm:
  insertErrHsptlRecords: "insertErrHsptlRecordsQueue"
  deleteErrHsptlRecords: "deleteErrHsptlRecordsQueue"
watermark:
  timezone: "GMT"