batch:
  aggregatorSize: "100"
errHsptl:
  maxRetries: "5"
  retrieveLimit: "100"
orgName: "MNA-Tech"
projectName: "mna-oppty-mirroring-accelerator"
scheduler:
  main:
    cronExpression: "0 0 * * * ?"
    timezone: "GMT"
  retry:
    cronExpression: "0 0/10 * * * ?"
    timezone: "GMT"
smtp:
  toAddress: "error_notifications@test.com"
source:
  pbEntryId:
    productA: "01uKa00000AeCAcIAN"
    productB: "01uKa00000AeCAeIAN"
    productC: "01uKa00000AeCAdIAN"
    productD: "01uKa00000AeDIxIAN"
target:
  pbEntryId:
    productA: "01ugL0000020n61QAA"
    productB: "01ugL0000020n1BQAQ"
    productC: "01ugL0000020n62QAA"
    productD: "01ugL000002193JQAQ"
vm:
  errHsptlRecordCreate: "errHsptlRecordCreateRequest"
  errHsptlRecordDelete: "errHsptlRecordDeleteRequest"
watermark:
  timezone: "GMT"