orgName: "MNA-Tech"
projectName: "mna-oppty-mirror-accel"
httpListener:
  port: "8084"
  readTimeout: "30000"
batch:
  aggregatorSize: "100"
errHsptl:
  maxRetries: "5"
  retrieveLimit: "100"
scheduler:
  main:
    cronExpression: "0 0 * * * ?"
    timezone: "GMT"
  retry:
    cronExpression: "0 0/10 * * * ?"
    timezone: "GMT"
amq:
  errHsptlInsertRecordsQueue: "errHsptlInsertRecordsQueue"
  errHsptlRemoveRecordsQueue: "errHsptlRemoveRecordsQueue"
  clientId: "4e9fee5567394e3baaa0daf8c5ccec3c"
  url: https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/a0341e01-9078-43f6-86f4-72a5cfb1db90/environments/a796e386-3ec6-4ce5-935a-377353244b2c
smtp:
  hostname: "smtp.gmail.com"
  port: "587"
  toEmailAddresses: "cbyam.ms@gmail.com"
  subject:
    errHsptlError: "[mna-oppty-mirror-accel] Error Hospital API Error"
    batchSummary: "[mna-oppty-mirror-accel] Batch Job Completion Summary"
    schedulerError: "[mna-oppty-mirror-accel] Scheduler Error"
watermark:
  timezone: "GMT"
error:
  defaultType: "UNKNOWN_ERROR"
  defaultMessage: "An unknown error occurred"
  defaultDescription: "An error occurred during the Opportunity mirroring process; please check integration logs with this transaction Id for more details"
src:
  pbEntryId:
    C: "01uKa00000AeCAcIAN"
    OT: "01uKa00000AeCAeIAN"
    OG: "01uKa00000AeCAdIAN"
    DT: "01uKa00000AeqiSIAR"
tgt:
  pbEntryId:
    C: "01ugL000002WgsbQAC"
    OT: "01ugL000002WgkXQAS"
    OG: "01ugL000002WgkYQAS"
    DT: "01ugL000002X6OrQAK"