source:
  password: "![ool73ANjwr8e5ijlx84Xnbo1r4wR7lwrXQj2r2KO9j4=]"
  securityToken: "![kjZpHB/djraT2yDo/ORkEryLpsW3WBJpR84rcO4PhOc=]"
  username: "![feep8wwauiCMo2DNSQ35vRZMNTuwY8Ouk6Mghw1jOLs=]"
target:
  password: "![8HS0lZOvobP6HArfI0QLLzwI4mkayO2MooM8Rh2Ulv4=]"
  securityToken: "![oAL/WGX/kETlfgnmFnZ+943fX5wv0IrG/Rmmw27Nysc=]"
  username: "![feep8wwauiCMo2DNSQ35vX2k5qaJODrJq5ciDOKaull4gZpjqzaOoYxoLa3WoF6M]"