source:
  password: "![NmZu95WSGKKGgtMl4Ib9iFoo6lip4sTDNv4djhhQccs=]"
  securityToken: "![wqG+ejibYXwEDkmTCxDM0Hlg8JHWEzSwJZy179Zdtbo=]"
  username: "![feep8wwauiCMo2DNSQ35vRZMNTuwY8Ouk6Mghw1jOLs=]"
target:
  password: "![LFYVOWChSOLWuo9iRRbguZ7xBgC2O4xZZmMUzYRV8j4=]"
  securityToken: "![HZAdt8olCa/bFH6ml8uwS4DjFcpMQ4PifLNqexuCSKU=]"
  username: "![/5uN8W6uuwatldP62wMCbxARuT8ntBha+iTwKaLxZ90=]"